oracle_wms:
  target: dev
  outputs:
    dev:
      type: oracle
      host: "{{ env_var('TARGET_ORACLE_HOST') }}"
      port: "{{ env_var('TARGET_ORACLE_PORT') | int }}"
      service: "{{ env_var('TARGET_ORACLE_SERVICE_NAME') }}"
      user: "{{ env_var('TARGET_ORACLE_USERNAME') }}"
      password: "{{ env_var('TARGET_ORACLE_PASSWORD') }}"
      schema: "{{ env_var('TARGET_ORACLE_SCHEMA', 'WMS_SYNC') }}"
      threads: "{{ env_var('DBT_THREADS', 4) | int }}"
      keepalives_idle: 0
      search_path_prefix: "{{ env_var('TARGET_ORACLE_SCHEMA', 'WMS_SYNC') }}"

    staging:
      type: oracle
      host: "{{ env_var('STAGING_TARGET_ORACLE_HOST') }}"
      port: "{{ env_var('TARGET_ORACLE_PORT') | int }}"
      service: "{{ env_var('STAGING_TARGET_ORACLE_SERVICE_NAME') }}"
      user: "{{ env_var('STAGING_TARGET_ORACLE_USERNAME') }}"
      password: "{{ env_var('STAGING_TARGET_ORACLE_PASSWORD') }}"
      schema: "{{ env_var('STAGING_TARGET_ORACLE_SCHEMA', 'WMS_SYNC_STG') }}"
      threads: "{{ env_var('DBT_THREADS', 4) | int }}"
      keepalives_idle: 0
      search_path_prefix: "{{ env_var('STAGING_TARGET_ORACLE_SCHEMA', 'WMS_SYNC_STG') }}"

    prod:
      type: oracle
      host: "{{ env_var('PROD_TARGET_ORACLE_HOST') }}"
      port: "{{ env_var('TARGET_ORACLE_PORT') | int }}"
      service: "{{ env_var('PROD_TARGET_ORACLE_SERVICE_NAME') }}"
      user: "{{ env_var('PROD_TARGET_ORACLE_USERNAME') }}"
      password: "{{ env_var('PROD_TARGET_ORACLE_PASSWORD') }}"
      schema: "{{ env_var('PROD_TARGET_ORACLE_SCHEMA', 'WMS_SYNC') }}"
      threads: "{{ env_var('DBT_THREADS', 8) | int }}"
      keepalives_idle: 0
      search_path_prefix: "{{ env_var('PROD_TARGET_ORACLE_SCHEMA', 'WMS_SYNC') }}"
