version: 1
default_environment: dev
project_id: 50037a15-62c9-40c7-89cd-a0f28d139a1e
environments:
  - name: dev
  - name: staging
  - name: prod

plugins:
  extractors:
    - name: tap-oracle-wms-full
      namespace: tap_oracle_wms
      executable: flext-tap-oracle-wms
      config:
        # REST API Configuration - CORRECTED per FLEXT documentation
        base_url: $TAP_ORACLE_WMS_BASE_URL
        username: $TAP_ORACLE_WMS_USERNAME
        password: $TAP_ORACLE_WMS_PASSWORD
        company_code: $TAP_ORACLE_WMS_COMPANY_CODE
        facility_code: $TAP_ORACLE_WMS_FACILITY_CODE
        entities: ["allocation", "order_hdr", "order_dtl"]
        page_size: 500
        timeout: 600
        max_retries: 3
        enable_incremental: false
        start_date: "2024-01-01T00:00:00Z"

    - name: tap-oracle-wms-incremental
      namespace: tap_oracle_wms
      executable: flext-tap-oracle-wms
      config:
        # REST API Configuration - CORRECTED per FLEXT documentation
        base_url: $TAP_ORACLE_WMS_BASE_URL
        username: $TAP_ORACLE_WMS_USERNAME
        password: $TAP_ORACLE_WMS_PASSWORD
        company_code: $TAP_ORACLE_WMS_COMPANY_CODE
        facility_code: $TAP_ORACLE_WMS_FACILITY_CODE
        entities: ["allocation", "order_hdr", "order_dtl"]
        page_size: 500
        timeout: 600
        max_retries: 3
        enable_incremental: true
        replication_key: "mod_ts"
        start_date: "2024-01-01T00:00:00Z"

  loaders:
    - name: target-oracle-full
      namespace: target_oracle
      executable: flext-target-oracle
      config:
        # NESTED oracle_config - CORRECTED per FLEXT documentation
        oracle_config:
          host: $FLEXT_TARGET_ORACLE_HOST
          port: $FLEXT_TARGET_ORACLE_PORT
          service_name: $FLEXT_TARGET_ORACLE_SERVICE_NAME
          username: $FLEXT_TARGET_ORACLE_USERNAME
          password: $FLEXT_TARGET_ORACLE_PASSWORD
          protocol: $FLEXT_TARGET_ORACLE_PROTOCOL
        default_target_schema: $FLEXT_TARGET_ORACLE_SCHEMA
        batch_size: 5000
        load_method: "append_only"
        add_record_metadata: false

    - name: target-oracle-incremental
      namespace: target_oracle
      executable: flext-target-oracle
      config:
        # NESTED oracle_config - CORRECTED per FLEXT documentation
        oracle_config:
          host: $FLEXT_TARGET_ORACLE_HOST
          port: $FLEXT_TARGET_ORACLE_PORT
          service_name: $FLEXT_TARGET_ORACLE_SERVICE_NAME
          username: $FLEXT_TARGET_ORACLE_USERNAME
          password: $FLEXT_TARGET_ORACLE_PASSWORD
          protocol: $FLEXT_TARGET_ORACLE_PROTOCOL
        default_target_schema: $FLEXT_TARGET_ORACLE_SCHEMA
        batch_size: 5000
        load_method: "upsert"
        add_record_metadata: false

jobs:
  - name: full-sync-job
    tasks:
      - tap-oracle-wms-full target-oracle-full

  - name: incremental-sync-job
    tasks:
      - tap-oracle-wms-incremental target-oracle-incremental

schedules:
  - name: full-sync-weekly
    job: full-sync-job
    interval: "@weekly"
    
  - name: incremental-sync-every-2-hours  
    job: incremental-sync-job
    interval: "0 */2 * * *"