version: 1
default_environment: dev
project_id: gruponos-meltano-native

environments:
- name: dev

plugins:
  extractors:
  - name: tap-oracle-wms-full
    namespace: tap_oracle_wms
    executable: /home/marlonsc/flext/.venv/bin/tap-oracle-wms
    config:
      base_url: $TAP_ORACLE_WMS_BASE_URL
      username: $TAP_ORACLE_WMS_USERNAME
      password: $TAP_ORACLE_WMS_PASSWORD
      entities: ["allocation", "order_hdr", "order_dtl"]
      page_size: 500
      force_full_table: true
      ordering: "-id"
      filter_mode: "id_recovery"
      timeout: 600
      
  - name: tap-oracle-wms-incremental
    namespace: tap_oracle_wms
    executable: /home/marlonsc/flext/.venv/bin/tap-oracle-wms
    config:
      base_url: $TAP_ORACLE_WMS_BASE_URL
      username: $TAP_ORACLE_WMS_USERNAME
      password: $TAP_ORACLE_WMS_PASSWORD
      entities: ["allocation", "order_hdr", "order_dtl"]
      page_size: 1000
      force_full_table: false
      ordering: "mod_ts"
      filter_mode: "incremental"
      lookback_minutes: 5

  loaders:
  - name: target-oracle-full
    namespace: target_oracle
    executable: /home/marlonsc/flext/.venv/bin/flext-target-oracle
    config:
      host: $FLEXT_TARGET_ORACLE_HOST
      port: 1522
      service_name: $FLEXT_TARGET_ORACLE_SERVICE_NAME
      username: $FLEXT_TARGET_ORACLE_USERNAME
      password: $FLEXT_TARGET_ORACLE_PASSWORD
      protocol: $FLEXT_TARGET_ORACLE_PROTOCOL
      ssl_server_dn_match: false
      batch_size_rows: 1000
      pool_size: 5
      add_record_metadata: false
      validate_records: false
      load_method: append-only
      ignore_pk_errors: true
      enable_historical_versioning: false
      table_prefix: WMS_
      debug_type_mapping: true

  - name: target-oracle-incremental
    namespace: target_oracle
    executable: /home/marlonsc/flext/.venv/bin/flext-target-oracle
    config:
      host: $FLEXT_TARGET_ORACLE_HOST
      port: 1522
      service_name: $FLEXT_TARGET_ORACLE_SERVICE_NAME
      username: $FLEXT_TARGET_ORACLE_USERNAME
      password: $FLEXT_TARGET_ORACLE_PASSWORD
      protocol: $FLEXT_TARGET_ORACLE_PROTOCOL
      ssl_server_dn_match: false
      batch_size_rows: 1000
      pool_size: 5
      add_record_metadata: false
      validate_records: false
      load_method: append-only
      ignore_pk_errors: true
      enable_historical_versioning: true
      historical_versioning_column: mod_ts
      table_prefix: WMS_

jobs:
  - name: full-sync-job
    tasks:
      - tap-oracle-wms-full target-oracle-full
      
  - name: incremental-sync-job
    tasks:
      - tap-oracle-wms-incremental target-oracle-incremental

schedules: []
