-- Optimized Oracle table for allocation
-- Generated on 2025-07-02T19:32:00.959265
DROP TABLE "OIC"."WMS_ALLOCATION" CASCADE CONSTRAINTS;

CREATE TABLE "OIC"."WMS_ALLOCATION"
  (
    "ID" NUMBER NOT NULL ENABLE,
    "ALLOCATION_DATE" TIMESTAMP(6),
    "ALLOCATION_ID" NUMBER,
    "ITEM_ID" NUMBER,
    "LOCATION_ID" NUMBER,
    "QTY_ALLOCATED" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "STATUS" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "USER_ID" NUMBER,
    "CREATE_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CREATE_TS" TIMESTAMP (6),
    "MOD_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "MOD_TS" TIMESTAMP (6) NOT NULL ENABLE,
    "TK_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE
     , CONSTRAINT "PK_WMS_ALLOCATION" PRIMARY KEY ("ID", "MOD_TS")
 ) ;

-- Performance indexes
CREATE INDEX "IDX_WMS_ALLOCATION_ALLOCATION_ID" ON "OIC"."WMS_ALLOCATION" ("ALLOCATION_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_CREATE_TS" ON "OIC"."WMS_ALLOCATION" ("CREATE_TS");
CREATE INDEX "IDX_WMS_ALLOCATION_ITEM_ID" ON "OIC"."WMS_ALLOCATION" ("ITEM_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_LOCATION_ID" ON "OIC"."WMS_ALLOCATION" ("LOCATION_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_MOD_TS" ON "OIC"."WMS_ALLOCATION" ("MOD_TS");
CREATE INDEX "IDX_WMS_ALLOCATION_TK_DATE" ON "OIC"."WMS_ALLOCATION" ("TK_DATE");
CREATE INDEX "IDX_WMS_ALLOCATION_USER_ID" ON "OIC"."WMS_ALLOCATION" ("USER_ID");
