-- Optimized Oracle table for allocation
-- Generated on 2025-07-03T17:38:45.807633
DROP TABLE "OIC"."WMS_ALLOCATION" CASCADE CONSTRAINTS;

CREATE TABLE "OIC"."WMS_ALLOCATION"
  (
    "ID" NUMBER NOT NULL ENABLE,
    "ALLOC_QTY" NUMBER,
    "ALLOC_UOM_ID" NUMBER,
    "ALLOC_UOM_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CARTONIZE_UOM_ID" NUMBER,
    "CARTONIZE_UOM_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "FINAL_OBLPN_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "FROM_INVENTORY_ID" NUMBER,
    "FROM_INVENTORY_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "IS_PICKING_FLG" NUMBER(1,0),
    "MHE_SYSTEM_ID" NUMBER,
    "OB_LPN_TYPE_ID" NUMBER,
    "ORDER_DTL_ID" NUMBER,
    "ORDER_DTL_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "PACKED_QTY" NUMBER,
    "PICK_LOCN_STR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "PICK_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "PICKED_TS" TIMESTAMP(6),
    "STATUS_ID" NUMBER,
    "TASK_ID" NUMBER,
    "TASK_SEQ_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "TO_INVENTORY_ID" NUMBER,
    "TO_INVENTORY_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "TYPE_ID" NUMBER,
    "TYPE_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "WAVE_ID" NUMBER,
    "CREATE_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CREATE_TS" TIMESTAMP (6),
    "MOD_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "MOD_TS" TIMESTAMP (6) NOT NULL ENABLE,
    "TK_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE
     , CONSTRAINT "PK_WMS_ALLOCATION" PRIMARY KEY ("ID", "MOD_TS")
 ) ;

-- Performance indexes
CREATE INDEX "IDX_WMS_ALLOCATION_ALLOC_UOM_ID" ON "OIC"."WMS_ALLOCATION" ("ALLOC_UOM_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_ALLOC_UOM_KEY" ON "OIC"."WMS_ALLOCATION" ("ALLOC_UOM_KEY");
CREATE INDEX "IDX_WMS_ALLOCATION_CARTONIZE_UOM_ID" ON "OIC"."WMS_ALLOCATION" ("CARTONIZE_UOM_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_CARTONIZE_UOM_KEY" ON "OIC"."WMS_ALLOCATION" ("CARTONIZE_UOM_KEY");
CREATE INDEX "IDX_WMS_ALLOCATION_CREATE_TS" ON "OIC"."WMS_ALLOCATION" ("CREATE_TS");
CREATE INDEX "IDX_WMS_ALLOCATION_FROM_INVENTORY_ID" ON "OIC"."WMS_ALLOCATION" ("FROM_INVENTORY_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_FROM_INVENTORY_KEY" ON "OIC"."WMS_ALLOCATION" ("FROM_INVENTORY_KEY");
CREATE INDEX "IDX_WMS_ALLOCATION_MHE_SYSTEM_ID" ON "OIC"."WMS_ALLOCATION" ("MHE_SYSTEM_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_MOD_TS" ON "OIC"."WMS_ALLOCATION" ("MOD_TS");
CREATE INDEX "IDX_WMS_ALLOCATION_OB_LPN_TYPE_ID" ON "OIC"."WMS_ALLOCATION" ("OB_LPN_TYPE_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_ORDER_DTL_ID" ON "OIC"."WMS_ALLOCATION" ("ORDER_DTL_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_ORDER_DTL_KEY" ON "OIC"."WMS_ALLOCATION" ("ORDER_DTL_KEY");
CREATE INDEX "IDX_WMS_ALLOCATION_PICKED_TS" ON "OIC"."WMS_ALLOCATION" ("PICKED_TS");
CREATE INDEX "IDX_WMS_ALLOCATION_STATUS_ID" ON "OIC"."WMS_ALLOCATION" ("STATUS_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_TASK_ID" ON "OIC"."WMS_ALLOCATION" ("TASK_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_TK_DATE" ON "OIC"."WMS_ALLOCATION" ("TK_DATE");
CREATE INDEX "IDX_WMS_ALLOCATION_TO_INVENTORY_ID" ON "OIC"."WMS_ALLOCATION" ("TO_INVENTORY_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_TO_INVENTORY_KEY" ON "OIC"."WMS_ALLOCATION" ("TO_INVENTORY_KEY");
CREATE INDEX "IDX_WMS_ALLOCATION_TYPE_ID" ON "OIC"."WMS_ALLOCATION" ("TYPE_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_TYPE_KEY" ON "OIC"."WMS_ALLOCATION" ("TYPE_KEY");
CREATE INDEX "IDX_WMS_ALLOCATION_WAVE_ID" ON "OIC"."WMS_ALLOCATION" ("WAVE_ID");
