-- Optimized Oracle table for allocation
-- Generated on 2025-07-02T13:32:18.263908
DROP TABLE "OIC"."WMS_ALLOCATION" CASCADE CONSTRAINTS;

CREATE TABLE "OIC"."WMS_ALLOCATION"
  (
    "ID" NUMBER NOT NULL ENABLE,
    "ALLOC_QTY" NUMBER,
    "ORDER_DTL_ID" NUMBER,
    "STATUS_ID" NUMBER,
    "CREATE_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CREATE_TS" TIMESTAMP (6),
    "MOD_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "MOD_TS" TIMESTAMP (6) NOT NULL ENABLE,
    "TK_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE
     , CONSTRAINT "PK_WMS_ALLOCATION" PRIMARY KEY ("ID", "MOD_TS")
 ) ;

-- Performance indexes
CREATE INDEX "IDX_WMS_ALLOCATION_CREATE_TS" ON "OIC"."WMS_ALLOCATION" ("CREATE_TS");
CREATE INDEX "IDX_WMS_ALLOCATION_MOD_TS" ON "OIC"."WMS_ALLOCATION" ("MOD_TS");
CREATE INDEX "IDX_WMS_ALLOCATION_ORDER_DTL_ID" ON "OIC"."WMS_ALLOCATION" ("ORDER_DTL_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_STATUS_ID" ON "OIC"."WMS_ALLOCATION" ("STATUS_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_TK_DATE" ON "OIC"."WMS_ALLOCATION" ("TK_DATE");
