-- All tables combined for execution
-- Optimized Oracle table for allocation
-- Generated on 2025-07-02T19:37:28.556684
DROP TABLE "OIC"."WMS_ALLOCATION" CASCADE CONSTRAINTS;

CREATE TABLE "OIC"."WMS_ALLOCATION"
  (
    "ID" NUMBER NOT NULL ENABLE,
    "ALLOC_QTY" NUMBER,
    "ALLOC_UOM_ID" NUMBER,
    "ALLOC_UOM_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CARTONIZE_UOM_ID" NUMBER,
    "CARTONIZE_UOM_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "FINAL_OBLPN_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "FROM_INVENTORY_ID" NUMBER,
    "FROM_INVENTORY_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "IS_PICKING_FLG" NUMBER(1,0),
    "MHE_SYSTEM_ID" NUMBER,
    "OB_LPN_TYPE_ID" NUMBER,
    "ORDER_DTL_ID" NUMBER,
    "ORDER_DTL_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "PACKED_QTY" NUMBER,
    "PICK_LOCN_STR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "PICK_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "PICKED_TS" TIMESTAMP(6),
    "STATUS_ID" NUMBER,
    "TASK_ID" NUMBER,
    "TASK_SEQ_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "TO_INVENTORY_ID" NUMBER,
    "TO_INVENTORY_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "TYPE_ID" NUMBER,
    "TYPE_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "WAVE_ID" NUMBER,
    "CREATE_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CREATE_TS" TIMESTAMP (6),
    "MOD_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "MOD_TS" TIMESTAMP (6) NOT NULL ENABLE,
    "TK_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE
     , CONSTRAINT "PK_WMS_ALLOCATION" PRIMARY KEY ("ID", "MOD_TS")
 ) ;

-- Performance indexes
CREATE INDEX "IDX_WMS_ALLOCATION_ALLOC_UOM_ID" ON "OIC"."WMS_ALLOCATION" ("ALLOC_UOM_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_ALLOC_UOM_KEY" ON "OIC"."WMS_ALLOCATION" ("ALLOC_UOM_KEY");
CREATE INDEX "IDX_WMS_ALLOCATION_CARTONIZE_UOM_ID" ON "OIC"."WMS_ALLOCATION" ("CARTONIZE_UOM_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_CARTONIZE_UOM_KEY" ON "OIC"."WMS_ALLOCATION" ("CARTONIZE_UOM_KEY");
CREATE INDEX "IDX_WMS_ALLOCATION_CREATE_TS" ON "OIC"."WMS_ALLOCATION" ("CREATE_TS");
CREATE INDEX "IDX_WMS_ALLOCATION_FROM_INVENTORY_ID" ON "OIC"."WMS_ALLOCATION" ("FROM_INVENTORY_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_FROM_INVENTORY_KEY" ON "OIC"."WMS_ALLOCATION" ("FROM_INVENTORY_KEY");
CREATE INDEX "IDX_WMS_ALLOCATION_MHE_SYSTEM_ID" ON "OIC"."WMS_ALLOCATION" ("MHE_SYSTEM_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_MOD_TS" ON "OIC"."WMS_ALLOCATION" ("MOD_TS");
CREATE INDEX "IDX_WMS_ALLOCATION_OB_LPN_TYPE_ID" ON "OIC"."WMS_ALLOCATION" ("OB_LPN_TYPE_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_ORDER_DTL_ID" ON "OIC"."WMS_ALLOCATION" ("ORDER_DTL_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_ORDER_DTL_KEY" ON "OIC"."WMS_ALLOCATION" ("ORDER_DTL_KEY");
CREATE INDEX "IDX_WMS_ALLOCATION_PICKED_TS" ON "OIC"."WMS_ALLOCATION" ("PICKED_TS");
CREATE INDEX "IDX_WMS_ALLOCATION_STATUS_ID" ON "OIC"."WMS_ALLOCATION" ("STATUS_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_TASK_ID" ON "OIC"."WMS_ALLOCATION" ("TASK_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_TK_DATE" ON "OIC"."WMS_ALLOCATION" ("TK_DATE");
CREATE INDEX "IDX_WMS_ALLOCATION_TO_INVENTORY_ID" ON "OIC"."WMS_ALLOCATION" ("TO_INVENTORY_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_TO_INVENTORY_KEY" ON "OIC"."WMS_ALLOCATION" ("TO_INVENTORY_KEY");
CREATE INDEX "IDX_WMS_ALLOCATION_TYPE_ID" ON "OIC"."WMS_ALLOCATION" ("TYPE_ID");
CREATE INDEX "IDX_WMS_ALLOCATION_TYPE_KEY" ON "OIC"."WMS_ALLOCATION" ("TYPE_KEY");
CREATE INDEX "IDX_WMS_ALLOCATION_WAVE_ID" ON "OIC"."WMS_ALLOCATION" ("WAVE_ID");
-- Optimized Oracle table for order_hdr
-- Generated on 2025-07-02T19:37:28.556995
DROP TABLE "OIC"."WMS_ORDER_HDR" CASCADE CONSTRAINTS;

CREATE TABLE "OIC"."WMS_ORDER_HDR"
  (
    "ID" NUMBER NOT NULL ENABLE,
    "BILLTO_CARRIER_ACCOUNT_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CARRIER_ACCOUNT_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "COMPANY_ID" NUMBER,
    "COMPANY_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CURRENCY_CODE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_ADDR" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_ADDR2" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_ADDR3" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_CITY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_CONTACT" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_COUNTRY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_DATE_1" TIMESTAMP(6),
    "CUST_DATE_2" TIMESTAMP(6),
    "CUST_DATE_3" TIMESTAMP(6),
    "CUST_DATE_4" TIMESTAMP(6),
    "CUST_DATE_5" TIMESTAMP(6),
    "CUST_DECIMAL_1" NUMBER,
    "CUST_DECIMAL_2" NUMBER,
    "CUST_DECIMAL_3" NUMBER,
    "CUST_DECIMAL_4" NUMBER,
    "CUST_DECIMAL_5" NUMBER,
    "CUST_EMAIL" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_1" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_2" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_3" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_4" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_5" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_LONG_TEXT_1" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_LONG_TEXT_2" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_LONG_TEXT_3" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_NAME" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_NUMBER_1" NUMBER,
    "CUST_NUMBER_2" NUMBER,
    "CUST_NUMBER_3" NUMBER,
    "CUST_NUMBER_4" NUMBER,
    "CUST_NUMBER_5" NUMBER,
    "CUST_PHONE_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_1" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_10" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_11" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_12" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_2" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_3" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_4" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_5" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_6" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_7" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_8" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_9" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_STATE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_ZIP" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUSTOMER_PO_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUSTOMER_PO_TYPE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "CUSTOMER_VENDOR_CODE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "CUSTOMS_BROKER_CONTACT_ID" NUMBER,
    "DEST_DEPT_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "DEST_FACILITY_ID" NUMBER,
    "DESTINATION_COMPANY_ID" NUMBER,
    "DESTINATION_COMPANY_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "DUTIES_CARRIER_ACCOUNT_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "DUTIES_PAYMENT_METHOD_ID" NUMBER,
    "ERP_SOURCE_HDR_REF" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ERP_SOURCE_SYSTEM_REF" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "EXP_DATE" TIMESTAMP(6),
    "EXTERNAL_ROUTE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "EXTERNALLY_PLANNED_LOAD_FLG" NUMBER(1,0),
    "FACILITY_ID" NUMBER,
    "FACILITY_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "GIFT_MSG" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "GROUP_REF" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "HOST_ALLOCATION_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "LPN_TYPE_CLASS" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "OB_LPN_TYPE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "OB_LPN_TYPE_ID" NUMBER,
    "ORD_DATE" TIMESTAMP(6),
    "ORDER_DTL_SET" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_DTL_SET_COUNT" NUMBER,
    "ORDER_DTL_SET_FILTER_PARAMS" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_DTL_SET_TOTAL" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_INSTRUCTIONS_SET" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_INSTRUCTIONS_SET_COUNT" NUMBER,
    "ORDER_LOCK_SET" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_NBR_TO_REPLACE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_SHIPPED_TS" TIMESTAMP(6),
    "ORDER_TYPE_ID" NUMBER,
    "ORDER_TYPE_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORIG_SALE_PRICE" NUMBER,
    "ORIG_SKU_COUNT" NUMBER,
    "PAYMENT_METHOD_ID" NUMBER,
    "PRIORITY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "RECORD_ORIGIN_CODE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "REF_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "REQ_SHIP_DATE" TIMESTAMP(6),
    "ROUTE_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SALES_CHANNEL" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SALES_ORDER_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SCHED_SHIP_DATE" TIMESTAMP(6),
    "SHIP_VIA_ID" NUMBER,
    "SHIP_VIA_REF_CODE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_ADDR" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_ADDR2" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_ADDR3" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_CITY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_CONTACT" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_COUNTRY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_EMAIL" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_FACILITY_ID" NUMBER,
    "SHIPTO_NAME" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_PHONE_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_STATE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_ZIP" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SPL_INSTR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "STAGE_LOCATION_ID" NUMBER,
    "START_SHIP_DATE" TIMESTAMP(6),
    "STATUS_ID" NUMBER,
    "STOP_SHIP_DATE" TIMESTAMP(6),
    "STOP_SHIP_FLG" NUMBER(1,0),
    "TMS_ORDER_HDR_REF" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "TMS_PARCEL_SHIPMENT_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "TOTAL_ORIG_ORD_QTY" NUMBER,
    "VAS_GROUP_CODE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "WORK_ORDER_KIT_ID" NUMBER,
    "CREATE_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CREATE_TS" TIMESTAMP (6),
    "MOD_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "MOD_TS" TIMESTAMP (6) NOT NULL ENABLE,
    "TK_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE
     , CONSTRAINT "PK_WMS_ORDER_HDR" PRIMARY KEY ("ID", "MOD_TS")
 ) ;

-- Performance indexes
CREATE INDEX "IDX_WMS_ORDER_HDR_COMPANY_ID" ON "OIC"."WMS_ORDER_HDR" ("COMPANY_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_COMPANY_KEY" ON "OIC"."WMS_ORDER_HDR" ("COMPANY_KEY");
CREATE INDEX "IDX_WMS_ORDER_HDR_CREATE_TS" ON "OIC"."WMS_ORDER_HDR" ("CREATE_TS");
CREATE INDEX "IDX_WMS_ORDER_HDR_CUSTOMS_BROKER_CONTACT_ID" ON "OIC"."WMS_ORDER_HDR" ("CUSTOMS_BROKER_CONTACT_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_DESTINATION_COMPANY_ID" ON "OIC"."WMS_ORDER_HDR" ("DESTINATION_COMPANY_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_DESTINATION_COMPANY_KEY" ON "OIC"."WMS_ORDER_HDR" ("DESTINATION_COMPANY_KEY");
CREATE INDEX "IDX_WMS_ORDER_HDR_DEST_FACILITY_ID" ON "OIC"."WMS_ORDER_HDR" ("DEST_FACILITY_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_DUTIES_PAYMENT_METHOD_ID" ON "OIC"."WMS_ORDER_HDR" ("DUTIES_PAYMENT_METHOD_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_FACILITY_ID" ON "OIC"."WMS_ORDER_HDR" ("FACILITY_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_FACILITY_KEY" ON "OIC"."WMS_ORDER_HDR" ("FACILITY_KEY");
CREATE INDEX "IDX_WMS_ORDER_HDR_MOD_TS" ON "OIC"."WMS_ORDER_HDR" ("MOD_TS");
CREATE INDEX "IDX_WMS_ORDER_HDR_OB_LPN_TYPE_ID" ON "OIC"."WMS_ORDER_HDR" ("OB_LPN_TYPE_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_ORDER_SHIPPED_TS" ON "OIC"."WMS_ORDER_HDR" ("ORDER_SHIPPED_TS");
CREATE INDEX "IDX_WMS_ORDER_HDR_ORDER_TYPE_ID" ON "OIC"."WMS_ORDER_HDR" ("ORDER_TYPE_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_ORDER_TYPE_KEY" ON "OIC"."WMS_ORDER_HDR" ("ORDER_TYPE_KEY");
CREATE INDEX "IDX_WMS_ORDER_HDR_PAYMENT_METHOD_ID" ON "OIC"."WMS_ORDER_HDR" ("PAYMENT_METHOD_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_SHIPTO_FACILITY_ID" ON "OIC"."WMS_ORDER_HDR" ("SHIPTO_FACILITY_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_SHIP_VIA_ID" ON "OIC"."WMS_ORDER_HDR" ("SHIP_VIA_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_STAGE_LOCATION_ID" ON "OIC"."WMS_ORDER_HDR" ("STAGE_LOCATION_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_STATUS_ID" ON "OIC"."WMS_ORDER_HDR" ("STATUS_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_TK_DATE" ON "OIC"."WMS_ORDER_HDR" ("TK_DATE");
CREATE INDEX "IDX_WMS_ORDER_HDR_WORK_ORDER_KIT_ID" ON "OIC"."WMS_ORDER_HDR" ("WORK_ORDER_KIT_ID");
-- Optimized Oracle table for order_dtl
-- Generated on 2025-07-02T19:37:28.558517
DROP TABLE "OIC"."WMS_ORDER_DTL" CASCADE CONSTRAINTS;

CREATE TABLE "OIC"."WMS_ORDER_DTL"
  (
    "ID" NUMBER NOT NULL ENABLE,
    "ALLOC_QTY" NUMBER,
    "BATCH_NUMBER_ID" NUMBER,
    "COST" NUMBER,
    "CUST_DATE_1" TIMESTAMP(6),
    "CUST_DATE_2" TIMESTAMP(6),
    "CUST_DATE_3" TIMESTAMP(6),
    "CUST_DATE_4" TIMESTAMP(6),
    "CUST_DATE_5" TIMESTAMP(6),
    "CUST_DECIMAL_1" NUMBER,
    "CUST_DECIMAL_2" NUMBER,
    "CUST_DECIMAL_3" NUMBER,
    "CUST_DECIMAL_4" NUMBER,
    "CUST_DECIMAL_5" NUMBER,
    "CUST_FIELD_1" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_2" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_3" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_4" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_5" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_LONG_TEXT_1" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_LONG_TEXT_2" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_LONG_TEXT_3" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_NUMBER_1" NUMBER,
    "CUST_NUMBER_2" NUMBER,
    "CUST_NUMBER_3" NUMBER,
    "CUST_NUMBER_4" NUMBER,
    "CUST_NUMBER_5" NUMBER,
    "CUST_SHORT_TEXT_1" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_10" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_11" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_12" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_2" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_3" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_4" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_5" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_6" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_7" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_8" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_9" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "DEST_FACILITY_ATTR_A" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "DEST_FACILITY_ATTR_B" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "DEST_FACILITY_ATTR_C" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ERP_FULFILLMENT_LINE_REF" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ERP_SOURCE_LINE_REF" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ERP_SOURCE_SHIPMENT_REF" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "EXTERNALLY_PLANNED_LOAD_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "HOST_OB_LPN_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "INTERNAL_TEXT_FIELD_1" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "INVN_ATTR_ID" NUMBER,
    "INVN_ATTR_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ITEM_ID" NUMBER,
    "ITEM_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "LOCK_CODE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "MAX_SHIPPING_TOLERANCE_PERCENTAGE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "MIN_SHIPPING_TOLERANCE_PERCENTAGE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "OB_LPN_TYPE_ID" NUMBER,
    "ORD_QTY" NUMBER,
    "ORDER_DTL_ORIGINAL_SEQ_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_ID" NUMBER,
    "ORDER_INSTRUCTIONS_SET" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_INSTRUCTIONS_SET_COUNT" NUMBER,
    "ORDER_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDERED_UOM_ID" NUMBER,
    "ORDERED_UOM_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDERED_UOM_QTY" NUMBER,
    "ORIG_ITEM_CODE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "ORIG_ORD_QTY" NUMBER,
    "ORIG_ORDER_REF_ID" NUMBER,
    "PLANNED_PARCEL_SHIPMENT_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "PO_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "REF_NBR_1" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "REQ_CNTR_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "REQ_PALLET_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "REQUIRED_SERIAL_NBR_SET" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "REQUIRED_SERIAL_NBR_SET_COUNT" NUMBER,
    "SALE_PRICE" NUMBER,
    "SEQ_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SERIAL_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIP_REQUEST_LINE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPMENT_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SPL_INSTR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "STATUS_ID" NUMBER,
    "UNIT_DECLARED_VALUE" NUMBER,
    "UOM_ID" NUMBER,
    "UOM_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "VAS_ACTIVITY_CODE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "VOUCHER_AMOUNT" NUMBER,
    "VOUCHER_EXP_DATE" TIMESTAMP(6),
    "VOUCHER_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "VOUCHER_PRINT_COUNT" NUMBER,
    "CREATE_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CREATE_TS" TIMESTAMP (6),
    "MOD_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "MOD_TS" TIMESTAMP (6) NOT NULL ENABLE,
    "TK_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE
     , CONSTRAINT "PK_WMS_ORDER_DTL" PRIMARY KEY ("ID", "MOD_TS")
 ) ;

-- Performance indexes
CREATE INDEX "IDX_WMS_ORDER_DTL_BATCH_NUMBER_ID" ON "OIC"."WMS_ORDER_DTL" ("BATCH_NUMBER_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_CREATE_TS" ON "OIC"."WMS_ORDER_DTL" ("CREATE_TS");
CREATE INDEX "IDX_WMS_ORDER_DTL_INVN_ATTR_ID" ON "OIC"."WMS_ORDER_DTL" ("INVN_ATTR_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_INVN_ATTR_KEY" ON "OIC"."WMS_ORDER_DTL" ("INVN_ATTR_KEY");
CREATE INDEX "IDX_WMS_ORDER_DTL_ITEM_ID" ON "OIC"."WMS_ORDER_DTL" ("ITEM_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_ITEM_KEY" ON "OIC"."WMS_ORDER_DTL" ("ITEM_KEY");
CREATE INDEX "IDX_WMS_ORDER_DTL_MOD_TS" ON "OIC"."WMS_ORDER_DTL" ("MOD_TS");
CREATE INDEX "IDX_WMS_ORDER_DTL_OB_LPN_TYPE_ID" ON "OIC"."WMS_ORDER_DTL" ("OB_LPN_TYPE_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_ORDERED_UOM_ID" ON "OIC"."WMS_ORDER_DTL" ("ORDERED_UOM_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_ORDERED_UOM_KEY" ON "OIC"."WMS_ORDER_DTL" ("ORDERED_UOM_KEY");
CREATE INDEX "IDX_WMS_ORDER_DTL_ORDER_ID" ON "OIC"."WMS_ORDER_DTL" ("ORDER_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_ORDER_KEY" ON "OIC"."WMS_ORDER_DTL" ("ORDER_KEY");
CREATE INDEX "IDX_WMS_ORDER_DTL_ORIG_ORDER_REF_ID" ON "OIC"."WMS_ORDER_DTL" ("ORIG_ORDER_REF_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_STATUS_ID" ON "OIC"."WMS_ORDER_DTL" ("STATUS_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_TK_DATE" ON "OIC"."WMS_ORDER_DTL" ("TK_DATE");
CREATE INDEX "IDX_WMS_ORDER_DTL_UOM_ID" ON "OIC"."WMS_ORDER_DTL" ("UOM_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_UOM_KEY" ON "OIC"."WMS_ORDER_DTL" ("UOM_KEY");
