-- Optimized Oracle table for order_hdr
-- Generated on 2025-07-03T09:26:37.424671
DROP TABLE "OIC"."WMS_ORDER_HDR" CASCADE CONSTRAINTS;

CREATE TABLE "OIC"."WMS_ORDER_HDR"
  (
    "ID" NUMBER NOT NULL ENABLE,
    "BILLTO_CARRIER_ACCOUNT_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CARRIER_ACCOUNT_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "COMPANY_ID" NUMBER,
    "COMPANY_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CURRENCY_CODE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_ADDR" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_ADDR2" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_ADDR3" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_CITY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_CONTACT" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_COUNTRY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_DATE_1" TIMESTAMP(6),
    "CUST_DATE_2" TIMESTAMP(6),
    "CUST_DATE_3" TIMESTAMP(6),
    "CUST_DATE_4" TIMESTAMP(6),
    "CUST_DATE_5" TIMESTAMP(6),
    "CUST_DECIMAL_1" NUMBER,
    "CUST_DECIMAL_2" NUMBER,
    "CUST_DECIMAL_3" NUMBER,
    "CUST_DECIMAL_4" NUMBER,
    "CUST_DECIMAL_5" NUMBER,
    "CUST_EMAIL" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_1" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_2" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_3" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_4" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_5" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_LONG_TEXT_1" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_LONG_TEXT_2" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_LONG_TEXT_3" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_NAME" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_NUMBER_1" NUMBER,
    "CUST_NUMBER_2" NUMBER,
    "CUST_NUMBER_3" NUMBER,
    "CUST_NUMBER_4" NUMBER,
    "CUST_NUMBER_5" NUMBER,
    "CUST_PHONE_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_1" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_10" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_11" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_12" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_2" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_3" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_4" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_5" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_6" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_7" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_8" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_9" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_STATE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_ZIP" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUSTOMER_PO_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUSTOMER_PO_TYPE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "CUSTOMER_VENDOR_CODE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "CUSTOMS_BROKER_CONTACT_ID" NUMBER,
    "DEST_DEPT_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "DEST_FACILITY_ID" NUMBER,
    "DESTINATION_COMPANY_ID" NUMBER,
    "DESTINATION_COMPANY_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "DUTIES_CARRIER_ACCOUNT_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "DUTIES_PAYMENT_METHOD_ID" NUMBER,
    "ERP_SOURCE_HDR_REF" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ERP_SOURCE_SYSTEM_REF" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "EXP_DATE" TIMESTAMP(6),
    "EXTERNAL_ROUTE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "EXTERNALLY_PLANNED_LOAD_FLG" NUMBER(1,0),
    "FACILITY_ID" NUMBER,
    "FACILITY_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "GIFT_MSG" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "GROUP_REF" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "HOST_ALLOCATION_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "LPN_TYPE_CLASS" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "OB_LPN_TYPE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "OB_LPN_TYPE_ID" NUMBER,
    "ORD_DATE" TIMESTAMP(6),
    "ORDER_DTL_SET" VARCHAR2(500 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_DTL_SET_COUNT" NUMBER,
    "ORDER_DTL_SET_FILTER_PARAMS" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_DTL_SET_TOTAL" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_INSTRUCTIONS_SET" VARCHAR2(500 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_INSTRUCTIONS_SET_COUNT" NUMBER,
    "ORDER_LOCK_SET" VARCHAR2(500 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_NBR_TO_REPLACE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_SHIPPED_TS" TIMESTAMP(6),
    "ORDER_TYPE_ID" NUMBER,
    "ORDER_TYPE_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORIG_SALE_PRICE" NUMBER,
    "ORIG_SKU_COUNT" NUMBER,
    "PAYMENT_METHOD_ID" NUMBER,
    "PRIORITY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "RECORD_ORIGIN_CODE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "REF_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "REQ_SHIP_DATE" TIMESTAMP(6),
    "ROUTE_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SALES_CHANNEL" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SALES_ORDER_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SCHED_SHIP_DATE" TIMESTAMP(6),
    "SHIP_VIA_ID" NUMBER,
    "SHIP_VIA_REF_CODE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_ADDR" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_ADDR2" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_ADDR3" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_CITY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_CONTACT" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_COUNTRY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_EMAIL" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_FACILITY_ID" NUMBER,
    "SHIPTO_NAME" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_PHONE_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_STATE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPTO_ZIP" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SPL_INSTR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "STAGE_LOCATION_ID" NUMBER,
    "START_SHIP_DATE" TIMESTAMP(6),
    "STATUS_ID" NUMBER,
    "STOP_SHIP_DATE" TIMESTAMP(6),
    "STOP_SHIP_FLG" NUMBER(1,0),
    "TMS_ORDER_HDR_REF" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "TMS_PARCEL_SHIPMENT_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "TOTAL_ORIG_ORD_QTY" NUMBER,
    "VAS_GROUP_CODE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "WORK_ORDER_KIT_ID" NUMBER,
    "CREATE_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CREATE_TS" TIMESTAMP (6),
    "MOD_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "MOD_TS" TIMESTAMP (6) NOT NULL ENABLE,
    "TK_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE
     , CONSTRAINT "PK_WMS_ORDER_HDR" PRIMARY KEY ("ID", "MOD_TS")
 ) ;

-- Performance indexes
CREATE INDEX "IDX_WMS_ORDER_HDR_COMPANY_ID" ON "OIC"."WMS_ORDER_HDR" ("COMPANY_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_COMPANY_KEY" ON "OIC"."WMS_ORDER_HDR" ("COMPANY_KEY");
CREATE INDEX "IDX_WMS_ORDER_HDR_CREATE_TS" ON "OIC"."WMS_ORDER_HDR" ("CREATE_TS");
CREATE INDEX "IDX_WMS_ORDER_HDR_CUSTOMS_BROKER_CONTACT_ID" ON "OIC"."WMS_ORDER_HDR" ("CUSTOMS_BROKER_CONTACT_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_DESTINATION_COMPANY_ID" ON "OIC"."WMS_ORDER_HDR" ("DESTINATION_COMPANY_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_DESTINATION_COMPANY_KEY" ON "OIC"."WMS_ORDER_HDR" ("DESTINATION_COMPANY_KEY");
CREATE INDEX "IDX_WMS_ORDER_HDR_DEST_FACILITY_ID" ON "OIC"."WMS_ORDER_HDR" ("DEST_FACILITY_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_DUTIES_PAYMENT_METHOD_ID" ON "OIC"."WMS_ORDER_HDR" ("DUTIES_PAYMENT_METHOD_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_FACILITY_ID" ON "OIC"."WMS_ORDER_HDR" ("FACILITY_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_FACILITY_KEY" ON "OIC"."WMS_ORDER_HDR" ("FACILITY_KEY");
CREATE INDEX "IDX_WMS_ORDER_HDR_MOD_TS" ON "OIC"."WMS_ORDER_HDR" ("MOD_TS");
CREATE INDEX "IDX_WMS_ORDER_HDR_OB_LPN_TYPE_ID" ON "OIC"."WMS_ORDER_HDR" ("OB_LPN_TYPE_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_ORDER_SHIPPED_TS" ON "OIC"."WMS_ORDER_HDR" ("ORDER_SHIPPED_TS");
CREATE INDEX "IDX_WMS_ORDER_HDR_ORDER_TYPE_ID" ON "OIC"."WMS_ORDER_HDR" ("ORDER_TYPE_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_ORDER_TYPE_KEY" ON "OIC"."WMS_ORDER_HDR" ("ORDER_TYPE_KEY");
CREATE INDEX "IDX_WMS_ORDER_HDR_PAYMENT_METHOD_ID" ON "OIC"."WMS_ORDER_HDR" ("PAYMENT_METHOD_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_SHIPTO_FACILITY_ID" ON "OIC"."WMS_ORDER_HDR" ("SHIPTO_FACILITY_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_SHIP_VIA_ID" ON "OIC"."WMS_ORDER_HDR" ("SHIP_VIA_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_STAGE_LOCATION_ID" ON "OIC"."WMS_ORDER_HDR" ("STAGE_LOCATION_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_STATUS_ID" ON "OIC"."WMS_ORDER_HDR" ("STATUS_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_TK_DATE" ON "OIC"."WMS_ORDER_HDR" ("TK_DATE");
CREATE INDEX "IDX_WMS_ORDER_HDR_WORK_ORDER_KIT_ID" ON "OIC"."WMS_ORDER_HDR" ("WORK_ORDER_KIT_ID");
