-- Optimized Oracle table for order_dtl
-- Generated on 2025-07-03T17:38:45.808580
DROP TABLE "OIC"."WMS_ORDER_DTL" CASCADE CONSTRAINTS;

CREATE TABLE "OIC"."WMS_ORDER_DTL"
  (
    "ID" NUMBER NOT NULL ENABLE,
    "ALLOC_QTY" NUMBER,
    "BATCH_NUMBER_ID" NUMBER,
    "COST" NUMBER,
    "CUST_DATE_1" TIMESTAMP(6),
    "CUST_DATE_2" TIMESTAMP(6),
    "CUST_DATE_3" TIMESTAMP(6),
    "CUST_DATE_4" TIMESTAMP(6),
    "CUST_DATE_5" TIMESTAMP(6),
    "CUST_DECIMAL_1" NUMBER,
    "CUST_DECIMAL_2" NUMBER,
    "CUST_DECIMAL_3" NUMBER,
    "CUST_DECIMAL_4" NUMBER,
    "CUST_DECIMAL_5" NUMBER,
    "CUST_FIELD_1" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_2" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_3" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_4" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_FIELD_5" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_LONG_TEXT_1" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_LONG_TEXT_2" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_LONG_TEXT_3" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_NUMBER_1" NUMBER,
    "CUST_NUMBER_2" NUMBER,
    "CUST_NUMBER_3" NUMBER,
    "CUST_NUMBER_4" NUMBER,
    "CUST_NUMBER_5" NUMBER,
    "CUST_SHORT_TEXT_1" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_10" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_11" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_12" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_2" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_3" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_4" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_5" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_6" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_7" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_8" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CUST_SHORT_TEXT_9" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "DEST_FACILITY_ATTR_A" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "DEST_FACILITY_ATTR_B" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "DEST_FACILITY_ATTR_C" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ERP_FULFILLMENT_LINE_REF" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ERP_SOURCE_LINE_REF" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ERP_SOURCE_SHIPMENT_REF" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "EXTERNALLY_PLANNED_LOAD_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "HOST_OB_LPN_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "INTERNAL_TEXT_FIELD_1" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "INVN_ATTR_ID" NUMBER,
    "INVN_ATTR_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ITEM_ID" NUMBER,
    "ITEM_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "LOCK_CODE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "MAX_SHIPPING_TOLERANCE_PERCENTAGE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "MIN_SHIPPING_TOLERANCE_PERCENTAGE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "OB_LPN_TYPE_ID" NUMBER,
    "ORD_QTY" NUMBER,
    "ORDER_DTL_ORIGINAL_SEQ_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_ID" NUMBER,
    "ORDER_INSTRUCTIONS_SET" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_INSTRUCTIONS_SET_COUNT" NUMBER,
    "ORDER_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDERED_UOM_ID" NUMBER,
    "ORDERED_UOM_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDERED_UOM_QTY" NUMBER,
    "ORIG_ITEM_CODE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "ORIG_ORD_QTY" NUMBER,
    "ORIG_ORDER_REF_ID" NUMBER,
    "PLANNED_PARCEL_SHIPMENT_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "PO_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "REF_NBR_1" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "REQ_CNTR_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "REQ_PALLET_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "REQUIRED_SERIAL_NBR_SET" VARCHAR2(4000 CHAR) COLLATE "USING_NLS_COMP",
    "REQUIRED_SERIAL_NBR_SET_COUNT" NUMBER,
    "SALE_PRICE" NUMBER,
    "SEQ_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SERIAL_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIP_REQUEST_LINE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SHIPMENT_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "SPL_INSTR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "STATUS_ID" NUMBER,
    "UNIT_DECLARED_VALUE" NUMBER,
    "UOM_ID" NUMBER,
    "UOM_KEY" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "VAS_ACTIVITY_CODE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP",
    "VOUCHER_AMOUNT" NUMBER,
    "VOUCHER_EXP_DATE" TIMESTAMP(6),
    "VOUCHER_NBR" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "VOUCHER_PRINT_COUNT" NUMBER,
    "CREATE_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CREATE_TS" TIMESTAMP (6),
    "MOD_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "MOD_TS" TIMESTAMP (6) NOT NULL ENABLE,
    "TK_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE
     , CONSTRAINT "PK_WMS_ORDER_DTL" PRIMARY KEY ("ID", "MOD_TS")
 ) ;

-- Performance indexes
CREATE INDEX "IDX_WMS_ORDER_DTL_BATCH_NUMBER_ID" ON "OIC"."WMS_ORDER_DTL" ("BATCH_NUMBER_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_CREATE_TS" ON "OIC"."WMS_ORDER_DTL" ("CREATE_TS");
CREATE INDEX "IDX_WMS_ORDER_DTL_INVN_ATTR_ID" ON "OIC"."WMS_ORDER_DTL" ("INVN_ATTR_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_INVN_ATTR_KEY" ON "OIC"."WMS_ORDER_DTL" ("INVN_ATTR_KEY");
CREATE INDEX "IDX_WMS_ORDER_DTL_ITEM_ID" ON "OIC"."WMS_ORDER_DTL" ("ITEM_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_ITEM_KEY" ON "OIC"."WMS_ORDER_DTL" ("ITEM_KEY");
CREATE INDEX "IDX_WMS_ORDER_DTL_MOD_TS" ON "OIC"."WMS_ORDER_DTL" ("MOD_TS");
CREATE INDEX "IDX_WMS_ORDER_DTL_OB_LPN_TYPE_ID" ON "OIC"."WMS_ORDER_DTL" ("OB_LPN_TYPE_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_ORDERED_UOM_ID" ON "OIC"."WMS_ORDER_DTL" ("ORDERED_UOM_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_ORDERED_UOM_KEY" ON "OIC"."WMS_ORDER_DTL" ("ORDERED_UOM_KEY");
CREATE INDEX "IDX_WMS_ORDER_DTL_ORDER_ID" ON "OIC"."WMS_ORDER_DTL" ("ORDER_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_ORDER_KEY" ON "OIC"."WMS_ORDER_DTL" ("ORDER_KEY");
CREATE INDEX "IDX_WMS_ORDER_DTL_ORIG_ORDER_REF_ID" ON "OIC"."WMS_ORDER_DTL" ("ORIG_ORDER_REF_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_STATUS_ID" ON "OIC"."WMS_ORDER_DTL" ("STATUS_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_TK_DATE" ON "OIC"."WMS_ORDER_DTL" ("TK_DATE");
CREATE INDEX "IDX_WMS_ORDER_DTL_UOM_ID" ON "OIC"."WMS_ORDER_DTL" ("UOM_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_UOM_KEY" ON "OIC"."WMS_ORDER_DTL" ("UOM_KEY");
