-- Optimized Oracle table for order_dtl
-- Generated on 2025-07-02T19:32:00.959440
DROP TABLE "OIC"."WMS_ORDER_DTL" CASCADE CONSTRAINTS;

CREATE TABLE "OIC"."WMS_ORDER_DTL"
  (
    "ID" NUMBER NOT NULL ENABLE,
    "ITEM_ID" NUMBER,
    "LINE_AMOUNT" NUMBER,
    "LINE_NUMBER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "ORDER_ID" NUMBER,
    "QTY_ORDERED" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "UNIT_PRICE" NUMBER,
    "CREATE_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CREATE_TS" TIMESTAMP (6),
    "MOD_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "MOD_TS" TIMESTAMP (6) NOT NULL ENABLE,
    "TK_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE
     , CONSTRAINT "PK_WMS_ORDER_DTL" PRIMARY KEY ("ID", "MOD_TS")
 ) ;

-- Performance indexes
CREATE INDEX "IDX_WMS_ORDER_DTL_CREATE_TS" ON "OIC"."WMS_ORDER_DTL" ("CREATE_TS");
CREATE INDEX "IDX_WMS_ORDER_DTL_ITEM_ID" ON "OIC"."WMS_ORDER_DTL" ("ITEM_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_MOD_TS" ON "OIC"."WMS_ORDER_DTL" ("MOD_TS");
CREATE INDEX "IDX_WMS_ORDER_DTL_ORDER_ID" ON "OIC"."WMS_ORDER_DTL" ("ORDER_ID");
CREATE INDEX "IDX_WMS_ORDER_DTL_TK_DATE" ON "OIC"."WMS_ORDER_DTL" ("TK_DATE");
