-- Optimized Oracle table for order_hdr
-- Generated on 2025-07-02T13:32:18.263981
DROP TABLE "OIC"."WMS_ORDER_HDR" CASCADE CONSTRAINTS;

CREATE TABLE "OIC"."WMS_ORDER_HDR"
  (
    "ID" NUMBER NOT NULL ENABLE,
    "CUSTOMER_ID" NUMBER,
    "ORDER_ID" NUMBER,
    "STATUS" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CREATE_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "CREATE_TS" TIMESTAMP (6),
    "MOD_USER" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
    "MOD_TS" TIMESTAMP (6) NOT NULL ENABLE,
    "TK_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE
     , CONSTRAINT "PK_WMS_ORDER_HDR" PRIMARY KEY ("ID", "MOD_TS")
 ) ;

-- Performance indexes
CREATE INDEX "IDX_WMS_ORDER_HDR_CREATE_TS" ON "OIC"."WMS_ORDER_HDR" ("CREATE_TS");
CREATE INDEX "IDX_WMS_ORDER_HDR_CUSTOMER_ID" ON "OIC"."WMS_ORDER_HDR" ("CUSTOMER_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_MOD_TS" ON "OIC"."WMS_ORDER_HDR" ("MOD_TS");
CREATE INDEX "IDX_WMS_ORDER_HDR_ORDER_ID" ON "OIC"."WMS_ORDER_HDR" ("ORDER_ID");
CREATE INDEX "IDX_WMS_ORDER_HDR_TK_DATE" ON "OIC"."WMS_ORDER_HDR" ("TK_DATE");
